volumes:
  postgres-db-test:
  redis-data-test:
  subscription-data-test:
  weather-data-test:
  email-data-test:
  gateway-data:

services:
  db-test:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    restart: always
    ports:
      - 6381:6379
    volumes:
      - redis-data-test:/data

  email-test:
    build:
      context: .
      dockerfile: apps/email/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    command: npm run test:email

  gateway-integration-test:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile.test
    env_file:
      - apps/gateway/.env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
      weather:
        condition: service_started
      subscription:
        condition: service_started
    command: npm run test:integration

  gateway-architecture-test:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    command: npm run test:architecture

  notification-test:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    command: npm run test:notification

  subscription-test:
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    command: npm run test:subscription

  weather-test:
    build:
      context: .
      dockerfile: apps/weather/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    command: npm run test:weather

  weather:
    container_name: weather
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    env_file:
      - apps/weather/.env.test
    ports:
      - 4001:4001
      - 5001:5001
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - .:/app
      - weather-data-test:/app/node_modules

  subscription:
    container_name: subscription
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile
    env_file:
      - apps/subscription/.env.test
    ports:
      - 4002:4002
      - 5002:5002
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
      email:
        condition: service_started
    volumes:
      - .:/app
      - subscription-data-test:/app/node_modules

  email:
    container_name: email
    build:
      context: .
      dockerfile: apps/email/Dockerfile
    env_file:
      - apps/email/.env.test
    ports:
      - 4000:4000
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - .:/app
      - email-data-test:/app/node_modules

  kafka-test:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-test:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-test:9092 --list',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-ui-test:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-test
    ports:
      - '8081:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-test:9092
      - DYNAMIC_CONFIG_ENABLED=true
