version: '3.8'

volumes:
  postgres-db-test:
  redis-data-test:

services:
  node-test:
    container_name: node-test
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - ./src:/home/node/app/src
      - ./test:/home/node/app/test
    command: sh -c "npx prisma migrate deploy --schema ./prisma/schema.prisma && npm run test && npm run test:e2e && npm run test:integration"

  db-test:
    container_name: db-test
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
    ports:
      - 5544:5432
    user: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5

  redis-test:
    container_name: redis-test
    image: redis:7-alpine
    restart: always
    ports:
      - 6381:6379
    volumes:
      - redis-data-test:/data
