name: Integration Test Pipeline

on:
  push:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: echo "${{ secrets.TEST_ENV_FILE }}" > .env.test

      - name: Create .env.test for email
        run: echo "${{ secrets.TEST_EMAIL_ENV_FILE }}" > apps/email/.env.test

      - name: Create .env.test for weather
        run: echo "${{ secrets.TEST_WEATHER_ENV_FILE }}" > apps/weather/.env.test

      - name: Create .env.test for subscription
        run: echo "${{ secrets.TEST_SUBSCRIPTION_ENV_FILE }}" > apps/subscription/.env.test

      - name: Create .env.test for gateway
        run: echo "${{ secrets.TEST_GATEWAY_ENV_FILE }}" > apps/gateway/.env.test
      
      - name: Build weather and email images
        run: docker compose -f docker-compose.test.yml build weather email

      - name: Run all integration tests via Docker Compose
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit gateway-integration-test

      - name: Clean up only gateway-integration-test
        if: always()
        run: docker compose -f docker-compose.test.yml rm -sf gateway-integration-test
