name: Lint Pipeline

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: |
          cd apps/subscription
          npx prisma generate

      - name: Run ESLint
        run: npm run lint
