name: Unit Test Pipeline

on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: echo "${{ secrets.TEST_ENV_FILE }}" > .env.test

      - name: Run all unit tests via Docker Compose
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit email-test notification-test subscription-test weather-test

      - name: Clean up Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
